### ISSUE TITLE
Updating the rock on LuaRocks

### ISSUE THREAD

**Issue by thefosk** [brentp/lua-stringy#3]
Can you please push the new version `stringy-0.3-1` to the LuaRocks repository?

The latest version available is still `0.2-1`: https://rocks.moonscript.org/modules/luarocks/stringy

Version `0.2-1` has some serious bugs, like `startswith` always returning `true`.

**Comment by brentp** [comment]
I think @ncopa has a fork with a rockspec file: https://github.com/ncopa/lua-stringy

**Comment by thefosk** [comment]
I see a rockspec file here too: https://github.com/brentp/lua-projects/blob/master/stringy/stringy-0.3-1.rockspec

The owner of the library on LuaRocks seems to be a user called `luarocks`. I don't know why is that, do you guys have access to https://rocks.moonscript.org/modules/luarocks/stringy to push a new version?

**Comment by brentp** [comment]
I don't, but if you want to fork the module and upload, that'd be great. I haven't worked with it (or lua) for quite some time. I think @ncopa 's version is preferable since it removes the sub-directory.

**Comment by brentp** [comment]
Looks like someone should tag a release on github and update the url in the rockspec since googlecode is shutting down.

**Comment by ncopa** [comment]
> do you guys have access to https://rocks.moonscript.org/modules/luarocks/stringy to push a new version?

@thefosk Seems like everyone has access to upload rockspecs there.
From https://rocks.moonscript.org/
> This is a place where anyone can upload and host Lua modules.

So you should be able to do it yourself.

**Comment by thefosk** [comment]
@ncopa if I upload the rockspec by myself I will create a duplicate, instead of adding a new version to the existing one. Since the username is `luarocks`, and you guys don't have access to that account on luarocks.org, I wonder if @hishamhm actually has access to it and can update it.

**Comment by ncopa** [comment]
@thefosk in any case, there is nothing stringy developers/maintainers can do about it.

**Comment by hishamhm** [comment]
The username being `luarocks` just means the rock wasn't claimed yet after the server conversion. Just let me know what luarocks.org username I should transfer stringy (and any other modules) to and I'll do it!

**Comment by brentp** [comment]
@thefosk I have updated the project name and added you as a collab for future changes.

@hishamhm can you just update the luarocks to point to the latest rockspec: https://raw.githubusercontent.com/brentp/lua-stringy/master/stringy/stringy-0.4.0.rockspec ?

**Comment by hishamhm** [comment]
@brentp ...but then I would have to do the same thing next time. The point of having users and accounts in luarocks.org now is precisely so I don't have to update hundreds of rockspecs myself. I don't scale! ;)

Please do open an account at luarocks.org and I'll be happy to transfer the rockspecs from the temporary `luarocks` account. Thank you!

**Comment by thefosk** [comment]
@brentp let me know if you had the chance to do this, or I will upload it with my account but is not really the best solution as it will create duplicates.

**Comment by brentp** [comment]
@hishamhm (and @thefosk) I created an account under user brentp on moonscript.org

**Comment by hishamhm** [comment]
@brentp, done, stringy is now under your account.

**Comment by brentp** [comment]
All, I think this the 0.4-0 rock is now on luarocks. My local copy is still installing 0.2-1 by default, but this is available: http://luarocks.org/repositories/rocks/stringy-0.4-0.src.rock
I'm not familiar with luarocks so maybe it just needs a while to propagate. Let me know any and I'll close this issue.

**Comment by thefosk** [comment]
I am experiencing the following error:

```shell
$ luarocks install stringy
Installing https://rocks.moonscript.org/stringy-0.4-0.src.rock...
Using https://rocks.moonscript.org/stringy-0.4-0.src.rock... switching to 'build' mode
export MACOSX_DEPLOYMENT_TARGET=10.5; gcc -O2 -fPIC -I/usr/local/include -c stringy.c -o stringy.o
clang: error: no such file or directory: 'stringy.c'
clang: error: no input files

Error: Build error: Failed compiling object stringy.o
```

**Comment by thefosk** [comment]
@brentp in the `rockspec` file this entry:

```
modules = {
       stringy = {
          sources = {"stringy.c"},
     }
```

should probably be:
```
modules = {
       stringy = {
          sources = {"stringy/stringy.c"},
     }
```

**Comment by brentp** [comment]
@thefosk I tried this. still unable to get it to work. Is the directory within the tarball required to have a certain path?

**Comment by hishamhm** [comment]
@brentp it is assumed to be the basename of the tarball, sans extensions. If it's not you can give it explicitly in source.dir. See:

https://github.com/keplerproject/luarocks/wiki/Rockspec-format#Build_rules

**Comment by brentp** [comment]
I updated the rock and it's workign now. thanks all.
